### PR TITLE
fix(admin): add log stream replicas to result of ListStorageNodes

### LINKED ISSUE #106: Incorrect response of ListStorageNodes RPC after restarting of admin server
### Current Behavior

Restarted admin server can send an incorrect list of storage nodes in response to ListStorageNodes RPC.

Admin server uses stats repository (`internal/admin/stats.(Repository)`) to get a list of storage nodes for the response of ListStorageNodes RPC. 
The admin server maintains the stats repository in memory. It fetches the metadata of storage nodes periodically and fills the stats repository by them. If the admin server was just restarted it has no storage nodes in the stats repository because its process was recreated. 
When someone requests ListStorageNodes RPC before fetching the storage node metadata again, the admin server can reply wrong information. It can cause the corruption of cluster configuration in case of rolling restarting of the cluster, for instance, an upgrade of the cluster.

### Expected Behavior

Admin should always send correct information about the storage nodes in the cluster.

### Steps To Reproduce

1. With varlog config...
2. Run '...'
3. See error...

### Environment

- Varlog version: v0.2.3
- OS:
- Architecture:

### Anything else

Anything that will give us more context about the issue that you are encountering!

### PR DESCRIPTION
**Pull request by ijsong**
### What this PR does

\#110 fixed the #106. However, it might not contain the log stream replicas in the result of
ListStorageNodes when the admin has been just restarted.
This patch uses the cluster metadata even if there is no information about the storage node in the
stats repository.

### Which issue(s) this PR resolves

Resolves #106

### Anything else

- - -
This change is [Reviewable](https://reviewable.io/reviews/kakao/varlog/112)

### CODE REVIEW

File: internal/admin/admin.go [hunk 1]
```diff
@@ -197,17 +219,52 @@ func (adm *Admin) listStorageNodes(ctx context.Context) ([]vmspb.StorageNodeMeta
...
+		if err != nil {
+			return nil, err
+		}
 		snms = append(snms, vmspb.StorageNodeMetadata{
 			StorageNodeMetadataDescriptor: snpb.StorageNodeMetadataDescriptor{
-				ClusterID:   adm.cid,
-				StorageNode: snd.StorageNode,
+				ClusterID:         adm.cid,
+				StorageNode:       snd.StorageNode,
+				LogStreamReplicas: replicasMap[snd.StorageNodeID],
```
Comment (hungryjang) [inline internal/admin/admin.go:267]: What is this metadata intended for?
If `StorageNodeMetadata.LastHeartbeatTime` is zero, kovadm ignores the metadata.
Even if it is not ignored, `LogStreamReplicaMetadataDescriptor` that cannot be used by kovadm because `UpdateTime` is 0.

Comment (ijsong) [reply internal/admin/admin.go:267]: Yes, you are right. It is not intended for the clients like KOV (Kafka On Varlog) admin.

As I said on messenger, its purpose is that restarted storage node checks mandatory directories that store log stream data. If there are no directories for log streams that are registered to the metadata repository, the storage node must not be started.

**Review by hungryjang — APPROVED** [review]
