### PR TITLE
fix(storagenode): fix a response of SyncInit when source replica was trimmed

### LINKED ISSUE #134: Synchronization of the log stream does not work.
### Current Behavior

Synchronization between two replicas doesn't work when the low watermark of the source replica is higher than it of the destination replica.

### Expected Behavior

The synchronization should work well.

### Steps To Reproduce

1. Create a log stream with more than two replicas.
2. Append 10 logs.
3. Trim the first five logs.
4. Update the log stream, which replaces one replica with a new one.
5. Sync error shows.

### Environment

- Varlog version: v0.3.1
- OS:
- Architecture:

### Anything else

It seems that SyncInit has the problem that the destination replica does not respect the first log position of the source replica. For example, the source replica calls SyncInit to send the destination replica a possible range of synchronization. The destination should reply with a valid range of synchronization, however, it doesn't.

### PR DESCRIPTION
**Pull request by ijsong**
### What this PR does

This patch fixed a response of `/varlog.snpb.Management/SyncInit` to respect trimmed source replica.

The cause of the problem was that the destination replica replied` uncommittedLLSNBegin` of itself
as the starting position of synchronization regardless of the source replica's condition. When the
source replica has been trimmed, the first log position of the synchronization range can be larger
than the `uncommittedLLSNBegin` of the destination replica. In this case, the destination should set
its `uncommittedLLSNBegin` and `uncommittedLLSNEnd` to the first log position of the synchronization
range.
Note that this synchronization makes the destination replica's all logs be removed and filled with
the new logs from the source replica. To reflect that the source replica has no logs, the
`localLowWatermark` and `localHighWatermark` of it should be set to invalid by `SyncInit`. They will
be changed by a commit triggered by synchronization.

### Which issue(s) this PR resolves

Resolves #134

### Anything else

- - -
This change is [Reviewable](https://reviewable.io/reviews/kakao/varlog/136)

### CODE REVIEW

**Review by hungryjang — COMMENTED** [review]
In this case, the destination replica has a hole log entry. How do we handle it? Has it already been considered?

**Comment by ijsong** [comment]
> In this case, the destination replica has a hole log entry. How do we handle it? Has it already been considered?

@hungryjang, I missed something below.

Since the hole had been already trimmed we should set `uncommittedLLSNBegin` and `uncommittedLLSNEnd` to the first log position of the synchronization's range. The version and high watermark will be updated by SyncReplicate.

However, I did not consider the local low and high watermarks. It could make the replica's metadata inaccurate due to wrong local watermarks. I fixed it and rebase the PR.
You should be careful of that the `Head` and `Tail` of the `/varlog.snpb.LogIO/LogStreamMetadata`'s results can be invalid.
I will publish a follow-up PR for this.

File: internal/storagenode/logstream/sync.go [hunk 1]
```diff
@@ -367,18 +367,32 @@ func (lse *Executor) SyncInit(_ context.Context, srcReplica varlogpb.LogStreamRe
...
+		// NOTE: The version and high watermark are not correct.
+		lse.lsc.storeReportCommitBase(types.InvalidVersion, types.InvalidGLSN, uncommittedLLSNBegin) // new uncommittedLLSNBegin
+		// NOTE: Since prefix logs has been trimmed, the local low and
+		// high watermarks are invalid. It will be reset by a commit
+		// triggered by SyncReplicate.
+		// It means that metadata of replica in the status of
+		// `LEARNING` is not credible because learning replica, which
+		// is the destination of synchronization, has invalid low and
+		// high watermarks.
+		lse.lsc.setLocalLowWatermark(varlogpb.InvalidLogEntryMeta())
```
Comment (hungryjang) [inline internal/storagenode/logstream/sync.go:389]: https://github.com/kakao/varlog/blob/c4d0c8d5926e834ffd6f5a7def2649bbed2a7075/internal/storagenode/logstream/executor.go#L539-L543

Because the new lowWatermark is larger than the stored latest log entry, it is unlikely that the previous log will be trimmed. Is it intended to be trimmed late?

Comment (ijsong) [reply internal/storagenode/logstream/sync.go:389]: Yes, it is. However, I think it will be a problem when recovering the log stream. I will fix it in this PR.

Comment (ijsong) [reply internal/storagenode/logstream/sync.go:389]: > Yes, it is. However, I think it will be a problem when recovering the log stream. I will fix it in this PR.

@hungryjang 
Unlike the above comment, I will fix it in follow-up PR because it needs too many changes.

For more explanation:
The hole can be a problem while the storage node reloads the log stream. To solve it, we can either remove the prefix logs trimmed or handle the hole while recovering. As you know, we need to improve the performance of recovering a log stream. So it can be easier to clean the logs up when processing SyncInit.
Another problem with cleaning the logs during handling SyncInit is that the current Trim API of the storage layer only supports GLSN, but SyncRange is only represented by LLSN. We should fix it up later.

Comment (hungryjang) [reply internal/storagenode/logstream/sync.go:389]: @ijsong Okay

**Review by hungryjang — APPROVED** [review]
