### PR TITLE
fix(metarepos): reportCollector handles invalid report propertly

### LINKED ISSUE #1011: metarepos: handle invalid report propertly
### Current Behavior

ReportCollector determines whether a report is invalid based on previously received report. If varlogsn is normal, reportCollector cannot receive a report with a lower version than the previously received report. So reportCollector panic for debugging.

### Expected Behavior

If varlogsn terminates abnormally, logstream data stored in pebble storage may be lost. In this case, report may be sent with a version lower than the committed version.

Therefore, reportCollector must be able to handle invalid reports propertly. 

### Steps To Reproduce

1. With varlog config...
2. Run '...'
3. See error...

### Environment

- Varlog version:
- OS:
- Architecture:

### Anything else

Anything that will give us more context about the issue that you are encountering!

### PR DESCRIPTION
**Pull request by hungryjang**
### What this PR does

This patch makes the report collector handle invalid reports properly. The report collector determines whether a report is invalid based on previously received report.

If valogsn terminates abnormally, the report collector may receive an invalid report and must handle it properly.

### Which issue(s) this PR resolves

Resolves #1011 

### Anything else

Include any links or documentation that might be helpful for reviewers.

### CODE REVIEW

File: internal/metarepos/report_collector_test.go [hunk 1]
```diff
@@ -602,6 +603,76 @@ func TestReportDedup(t *testing.T) {
 	})
 }
 
+func TestReportHandleInvalidReport(t *testing.T) {
+	a := NewDummyStorageNodeClientFactory(1, true)
+	mr := NewDummyMetadataRepository(a)
+
+	logger, _ := zap.NewDevelopment()
+	reportCollector := NewReportCollector(mr, DefaultRPCTimeout, newNopTelmetryStub(), logger)
+	reportCollector.Run() //nolint:errcheck,revive // TODO:: Handle an error returned.
```
Comment (ijsong) [inline internal/metarepos/report_collector_test.go:612]: Nit: How about handling returned errors like `require.NotNil(t, reportCollector.Run())`?
`(*reportCollector).Run()` is unlikely to return an error, so it appears to be a trivial matter. However, it would be preferable to avoid annotating `nolint`.

File: internal/metarepos/report_collector_test.go [hunk 2]
```diff
@@ -602,6 +603,76 @@ func TestReportDedup(t *testing.T) {
 	})
 }
 
+func TestReportHandleInvalidReport(t *testing.T) {
+	a := NewDummyStorageNodeClientFactory(1, true)
+	mr := NewDummyMetadataRepository(a)
+
+	logger, _ := zap.NewDevelopment()
```
Comment (ijsong) [inline internal/metarepos/report_collector_test.go:610]: Please use the `-v` test flag with zaptest to control verbosity.

File: internal/metarepos/report_collector.go [hunk 3]
```diff
@@ -681,14 +680,10 @@ func (rce *reportCollectExecutor) processReport(response *snpb.GetReportResponse
 			i++
 		} else {
 			if cur.Version < prev.Version {
-				fmt.Printf("invalid report prev:%v, cur:%v\n",
-					prev.Version, cur.Version)
-				rce.logger.Panic("invalid report",
+				rce.logger.Error("invalid report",
```
Comment (ijsong) [inline internal/metarepos/report_collector.go:683]: Could you please review this? This PR introduces a change, but it's not covered by the added test, TestReportHandleInvalidReport.

File: internal/metarepos/report_collector_test.go (hunk 2 above)
Comment (hungryjang) [reply internal/metarepos/report_collector_test.go]: `zaptest` looks good. thanx

File: internal/metarepos/report_collector.go (hunk 3 above)
Comment (hungryjang) [reply internal/metarepos/report_collector.go:683]: omg. Invalid report is filtered by other conditions. I fixed it.

**Review by ijsong — APPROVED** [review]
