### PR TITLE
fix(admin): contains all storage nodes registered to the cluster

### LINKED ISSUE #106: Incorrect response of ListStorageNodes RPC after restarting of admin server
### Current Behavior

Restarted admin server can send an incorrect list of storage nodes in response to ListStorageNodes RPC.

Admin server uses stats repository (`internal/admin/stats.(Repository)`) to get a list of storage nodes for the response of ListStorageNodes RPC. 
The admin server maintains the stats repository in memory. It fetches the metadata of storage nodes periodically and fills the stats repository by them. If the admin server was just restarted it has no storage nodes in the stats repository because its process was recreated. 
When someone requests ListStorageNodes RPC before fetching the storage node metadata again, the admin server can reply wrong information. It can cause the corruption of cluster configuration in case of rolling restarting of the cluster, for instance, an upgrade of the cluster.

### Expected Behavior

Admin should always send correct information about the storage nodes in the cluster.

### Steps To Reproduce

1. With varlog config...
2. Run '...'
3. See error...

### Environment

- Varlog version: v0.2.3
- OS:
- Architecture:

### Anything else

Anything that will give us more context about the issue that you are encountering!

### PR DESCRIPTION
**Pull request by ijsong**
### What this PR does

RPCs GetStorageNode and ListStorageNodes should contain all storage nodes registered to the cluster
even if the admin server is just restarted.
Previously, if the admin server was restarted the stats repository of the admin was flushed, thus,
it had a problem that the RPCs do not return all storage nodes after restarting.
This patch fixes the problem by using the cluster metadata fetched from the metadata repository. If
the metadata repository is not reachable transiently, the RPCs return an error with the status code
`Unavailable`.

### Which issue(s) this PR resolves

Resolves #106

### Anything else

- - -
This change is [Reviewable](https://reviewable.io/reviews/kakao/varlog/110)

### CODE REVIEW

File: internal/admin/admin.go [hunk 1]
```diff
@@ -163,17 +165,57 @@ func (adm *Admin) Metadata(ctx context.Context) (*varlogpb.MetadataDescriptor, e
...
+
+	snms := make([]vmspb.StorageNodeMetadata, 0, len(md.StorageNodes))
+	snmsMap := adm.statRepository.ListStorageNodes()
+	for _, snd := range md.StorageNodes {
+		if snm, ok := snmsMap[snd.StorageNodeID]; ok {
+			snms = append(snms, *snm)
+			continue
+		}
+		snms = append(snms, vmspb.StorageNodeMetadata{
+			StorageNodeMetadataDescriptor: snpb.StorageNodeMetadataDescriptor{
```
Comment (hungryjang) [inline internal/admin/admin.go:208]: Is it ok to not have the Storages metadata?

Comment (ijsong) [reply internal/admin/admin.go:208]: Zero values of some fields indicate that the admin does not check the heartbeat of the storage node yet.
Clients such as KOV should check whether they, for instance, LastHeartbeatTime are zero.

Comment (hungryjang) [reply internal/admin/admin.go:208]: `Admin.GetStorageNodes` uses `ListStorageNodes`.  So, there will be a lot of difference from before.
How about returning Unavailable if statRepository doesn't have all the metadata?

Comment (ijsong) [reply internal/admin/admin.go:208]: > `Admin.GetStorageNodes` uses `ListStorageNodes`. So, there will be a lot of difference from before. 

Originally, `GetStorageNodes` has been implemented by `ListStorageNodes`. So, it has been deprecated. Don't worry, you can use `GetStorageNodes` still.

> How about returning Unavailable if statRepository doesn't have all the metadata?

ListStorageNodes should be used by the storage node's operational script - `start_varlogsn.py`. For the storage node to decide whether it is registered to the cluster, ListStorageNodes must return all registered storage nodes regardless of reachability.

If the clients should know that the result of ListStorageNodes is partial, that is, some storage nodes are outage, it can check whether some of the result lists have zero value for LastHeartbeatTime.
However, if you think it is very cumbersome, please tell me. We are open to change or other approaches.

Comment (hungryjang) [reply internal/admin/admin.go:208]: What I mean is that kovadm works under the assumption that varlogadm always gives all metadata.
Okay. We will change the metadata processing logic in kovadm.

**Review by hungryjang — APPROVED** [review]
