### PR TITLE
fix(metarepos): new topic should start from MinGLSN

### LINKED ISSUE #427: metarepos: new Topic should start from MinGLSN
New topics should always be assigned a GLSN from MinGLSN. However, it is subject to the GLSN of a previously existing topic.

### PR DESCRIPTION
**Pull request by hungryjang**
### What this PR does
`LogStreamCommitResults.LastHighWatermark` returns the last HWM of the given topicID. However, if you search with an id larger than the largest topicID, the HWM of the previous topic is returned. So,  it is modified that InvalidHWM is returned in that case. 

### Which issue(s) this PR resolves

Resolves #427 

### Anything else

Include any links or documentation that might be helpful for reviewers.

### CODE REVIEW

File: proto/mrpb/raft_metadata_repository.go [hunk 1]
```diff
@@ -127,7 +127,7 @@ func (crs *LogStreamCommitResults) LastHighWatermark(topicID types.TopicID, hint
 		return crs.CommitResults[i].TopicID >= topicID+1
 	})
 
-	if i > 0 {
+	if i > 0 && crs.GetCommitResults()[i-1].TopicID == topicID {
```
Comment (ijsong) [inline proto/mrpb/raft_metadata_repository.go:130]: For this condition to work, the new topic ID should be higher than the existing one. Have I understood this correctly?

Comment (ijsong) [reply proto/mrpb/raft_metadata_repository.go:130]: I got it. Thanks for your explanation.

**Review by ijsong — APPROVED** [review]
