### PR TITLE
fix(admin): fix snwatcher handle heartbeat timeout

### LINKED ISSUE #1068: admin: There are cases where not all expected ls are sealed even if a storagenode heartbeat timeout occurs.
### Current Behavior

If the request to storagenode is delayed, all logstreams belonging to the storagenode cannot be sealed even if heartbeat timeout occurs. Also, since sealing is not requested to metarepos, commit results are piled up.

### Expected Behavior

All logstreams belonging to the storagenode should be sealed even if the request to the storagenode node is delayed. In particular, seal requests to metarepos should be handled with high priority.

### Steps To Reproduce

This occurs when there are two or more logstreams belonging to one storagenode and the storagenode has a delay for all requests.

### PR DESCRIPTION
**Pull request by hungryjang**
### Which issue(s) this PR resolves
This change fixes an issue where not all expected logstreams could be sealed within HandleHeartbeatTimeout due to storagenode delaying the response. Also fixes an issue where unexpected logstreams were being sealed by heartbeat false positives. In particular, it increases the priority of seal requests for metarepos so that commit results in metarepos do not pile up even if sealing is delayed.

Resolves #1068 #1069 

### Anything else

Include any links or documentation that might be helpful for reviewers.

### CODE REVIEW

File: internal/admin/snwatcher/snwatcher.go [hunk 1]
```diff
@@ -121,60 +118,69 @@ func (snw *StorageNodeWatcher) checkHeartbeat(ctx context.Context, now time.Time
 		go func(idx int) {
 			defer wg.Done()
 			snid := md.StorageNodes[idx].StorageNodeID
-			snmd, err := snw.snmgr.GetMetadata(ctx, snid)
+
+			mctx, cancel := context.WithTimeout(ctx, snw.heartbeatCheckDeadline)
+			defer cancel()
```
Comment (ijsong) [inline internal/admin/snwatcher/snwatcher.go:123]: mctx can be shared by all Go routines. It is safe as well as reduces heap allocations; RPC failure of a goroutine can't affect other goroutines' mctx use.

File: internal/admin/snwatcher/snwatcher.go [hunk 2]
```diff
@@ -121,60 +118,69 @@ func (snw *StorageNodeWatcher) checkHeartbeat(ctx context.Context, now time.Time
...
-func (snw *StorageNodeWatcher) handleHeartbeatTimeout(ctx context.Context, now time.Time) {
+func (snw *StorageNodeWatcher) handleHeartbeatTimeout(ctx context.Context) {
 	snw.mu.Lock()
 	defer snw.mu.Unlock()
 
 	var wg sync.WaitGroup
-	for snid, ts := range snw.hb {
-		if now.Sub(ts) > snw.tick*time.Duration(snw.heartbeatTimeout) {
+	for snid, cnt := range snw.hbFailcnt {
+		if time.Duration(cnt)*snw.tick > snw.heartbeatTimeout {
```
Comment (ijsong) [inline internal/admin/snwatcher/snwatcher.go:179]: It looks good to me right now. However, the `tick` is a fixed value and the elapsed time between each tick can be greater than the fixed tick. In this case, handling heartbeat timeout might be delayed slightly. Soon, we will have to investigate the failure detection mechanism more.

File: internal/admin/admin.go [hunk 3]
```diff
@@ -1093,19 +1110,41 @@ func (adm *Admin) removeMRPeer(ctx context.Context, raftURL string) error {
...
+				zap.Error(err))
+		}
+	}
+
+	hctx, cancel := context.WithTimeout(ctx, adm.storagenodeFailureHandleTimeout)
+	defer cancel()
+
+	for _, ls := range target {
+		adm.logger.Debug("seal due to heartbeat timeout", zap.Any("snid", snid), zap.Any("lsid", ls.LogStreamID))
+		_, _, _ = adm.seal(hctx, ls.TopicID, ls.LogStreamID)
```
[the remark this answers is not in the document]
Comment (hungryjang) [reply internal/admin/admin.go:1146]: I want `seal` to do the sealing job completely on its own. `sealMeta` is only used to prioritize sealing of metadata when performing sealing operations on multiple log streams in `HandleHeartbeatTimeout`.

File: internal/admin/config.go [hunk 4]
```diff
@@ -140,6 +143,12 @@ func WithLogStreamGCTimeout(logStreamGCTimeout time.Duration) Option {
 	})
 }
 
+func WithStorageNodeFailuleHandleTimeout(timeout time.Duration) Option {
+	return newFuncOption(func(cfg *config) {
+		cfg.storagenodeFailureHandleTimeout = timeout
+	})
+}
+
```
[the remark this answers is not in the document]
Comment (hungryjang) [reply internal/admin/config.go]: `WithStorageNodeFailureHandleTimeout` is used for testing. I am not sure if it should be used as a config in actual operation.

File: internal/admin/snwatcher/snwatcher.go (hunk 1 above)
Comment (hungryjang) [reply internal/admin/snwatcher/snwatcher.go]: You're right. Fixed.

File: cmd/varlogadm/flags.go [hunk 5]
```diff
@@ -68,4 +68,8 @@ var (
 		Name: "sn-watcher-report-deadline",
 		Envs: []string{"SN_WATCHER_REPORT_DEADLINE"},
 	}
+	flagSNWatcherHeartbeatTimeout = flags.FlagDesc{
+		Name: "sn-watcher-heartbeat-timeout",
+		Envs: []string{"SN_WATCHER_HEARTBEAT_TIMEOUT"},
+	}
```
[the remark this answers is not in the document]
Comment (hungryjang) [reply cmd/varlogadm/flags.go]: fixed.

File: internal/admin/snwatcher/snwatcher.go (hunk 2 above)
Comment (hungryjang) [reply internal/admin/snwatcher/snwatcher.go:180]: You are right. I focused on the number of heartbeat failures because our heartbeat check logic and subsequent processing logic cannot finish in a fixed amount of time.

**Review by ijsong — APPROVED** [review]
Nice work!
